sudo: false
language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
notifications:
  email: false
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - npm prune
script:
  - npm run validate
after_success:
  - npm run coverage
deploy:
  provider: surge
  project: ./dist/
  skip_cleanup: true
  domain: money-transfer-zanonnicola.surge.sh
